const $=s=>document.querySelector(s), money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const statusLabel={available:'Disponível',in_progress:'Em andamento',submitted:'Aguardando validação',closed:'Encerrada'};
let user=null,trips=[],activeTrip=null,capturedReceiptFile=null,cameraStream=null,editingExpenseId=null,editingAdminId=null,currentAdminResource=null,currentAdminItems=[];
async function request(url,options={}){const res=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const data=await res.json();if(!res.ok)throw new Error(data.error||'Não foi possível concluir.');return data}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function validCpf(value){const cpf=String(value||'').replace(/\D/g,'');if(cpf.length!==11||/^(\d)\1{10}$/.test(cpf))return false;for(let size=9;size<=10;size++){let sum=0;for(let i=0;i<size;i++)sum+=Number(cpf[i])*(size+1-i);if((sum*10)%11%10!==Number(cpf[size]))return false}return true}
function validEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(String(value||'').trim())}
function validCnpj(value){const cnpj=String(value||'').toUpperCase().replace(/[^A-Z0-9]/g,'');if(!/^[A-Z0-9]{12}\d{2}$/.test(cnpj)||/^(.)\1{13}$/.test(cnpj))return false;const weights=[[5,4,3,2,9,8,7,6,5,4,3,2],[6,5,4,3,2,9,8,7,6,5,4,3,2]];const digit=size=>{const sum=weights[size-12].reduce((total,weight,index)=>total+(cnpj.charCodeAt(index)-48)*weight,0),remainder=sum%11;return remainder<2?0:11-remainder};return digit(12)===Number(cnpj[12])&&digit(13)===Number(cnpj[13])}
function notify(message,type='success'){$('#notice').innerHTML=`<div class="notice ${type}">${esc(message)}</div>`;setTimeout(()=>$('#notice').innerHTML='',4000)}
async function boot(){try{user=(await request('/api/me')).user;if(!user){$('#login-view').hidden=false;return}showApp();await loadTrips()}catch{$('#login-view').hidden=false}}
function showApp(){$('#login-view').hidden=true;$('#app-view').hidden=false;$('#user-name').textContent=user.name;$('#company-name').textContent=user.company_name||'';$('#welcome-copy').textContent=user.role==='admin'?'Painel administrativo':'Bem-vindo, motorista';$('#role-badge').textContent=user.role==='admin'?'Administrador':'Motorista';$('#admin-nav').hidden=user.role!=='admin'}
async function loadTrips(){trips=(await request('/api/trips')).trips;activeTrip=null;$('#admin-view').hidden=true;$('#trip-detail').hidden=true;$('#trip-list').hidden=false;$('#page-title').textContent=user.role==='admin'?'Validação de viagens':'Suas viagens';setAdminTab('reviews');renderTrips()}
function renderTrips(){const visible=user.role==='admin'?trips.filter(t=>t.status==='submitted'||t.status==='closed'):trips;$('#trip-list').innerHTML=visible.length?visible.map(t=>`<article class="trip-summary" data-trip="${t.id}"><div><span class="label">${esc(t.code)}</span><h3>${esc(t.origin)} → ${esc(t.destination)}</h3><p>${esc(t.vehicle)} · ${esc(t.driver_name)}</p></div><div class="trip-side"><span class="status status-${t.status}">${statusLabel[t.status]}</span><strong>${money.format(t.total)}</strong></div></article>`).join(''):`<div class="empty">Nenhuma viagem nesta etapa.</div>`}
async function openTrip(id){const data=await request(`/api/trips/${id}`);activeTrip=data;$('#trip-list').hidden=true;$('#trip-detail').hidden=false;$('#page-title').textContent=`Viagem ${data.trip.code}`;renderDetail()}
function renderDetail(){const {trip,expenses}=activeTrip,total=expenses.reduce((s,e)=>s+e.amount,0),canEdit=user.role==='driver'&&trip.status==='in_progress';$('#trip-detail').innerHTML=`
  <button class="back secondary">← Voltar</button><section class="trip-card"><div class="trip-head"><div><span class="label">${esc(trip.code)}</span><strong>${esc(trip.origin)} → ${esc(trip.destination)}</strong></div><span class="status status-${trip.status}">${statusLabel[trip.status]}</span></div><div class="trip-meta"><span><small>Veículo</small>${esc(trip.vehicle)}</span><span><small>Orçamento</small>${money.format(trip.budget)}</span><span><small>Total</small>${money.format(total)}</span></div></section>
  ${trip.review_notes?`<div class="notice info"><strong>Observação da análise:</strong> ${esc(trip.review_notes)}</div>`:''}
  <div class="section-head"><div><span class="label">MOVIMENTAÇÃO</span><h2>Despesas (${expenses.length})</h2></div><div class="actions">${trip.status==='available'&&user.role==='driver'?'<button class="primary" data-action="start">Iniciar viagem</button>':''}${canEdit?'<button class="primary" data-action="add">+ Nova despesa</button>':''}</div></div>
  <section class="expense-list">${expenses.length?expenses.map(e=>`<article class="expense"><span class="expense-icon">${e.has_receipt?'▧':'—'}</span><div><h3>${esc(e.description)}</h3><p>${esc(e.category)} · ${new Date(e.occurred_at).toLocaleString('pt-BR')}</p></div><strong>${money.format(e.amount)}</strong><div class="expense-links">${e.has_receipt?`<button class="link" data-receipt="${e.id}">Ver nota</button>`:''}${e.latitude!=null&&e.longitude!=null?`<a class="link" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${e.latitude},${e.longitude}`)}" target="_blank" rel="noopener noreferrer">Ver no mapa</a>`:''}${canEdit?`<button class="edit-expense" data-edit="${e.id}">Editar</button><button class="delete" data-delete="${e.id}" aria-label="Excluir despesa">×</button>`:''}</div></article>`).join(''):'<div class="empty">Nenhuma despesa registrada.</div>'}</section>
  <div class="finish-actions">${canEdit&&expenses.length?'<button class="primary" data-action="submit">Enviar para validação</button>':''}${user.role==='admin'&&trip.status==='submitted'?'<textarea id="review-notes" placeholder="Observação da validação"></textarea><button class="secondary" data-action="reject">Solicitar correção</button><button class="primary" data-action="approve">Aprovar e encerrar</button>':''}</div>`}
async function refreshTrip(){await openTrip(activeTrip.trip.id)}
function openExpenseForm(expense=null){
 const form=$('#expense-form');form.reset();capturedReceiptFile=null;editingExpenseId=expense?.id||null;$('#expense-dialog-title').textContent=expense?'Editar despesa':'Registrar despesa';$('#save-expense').textContent=expense?'Salvar alterações':'Salvar despesa';$('#receipt-preview').hidden=true;
 const date=expense?new Date(expense.occurred_at):new Date();date.setMinutes(date.getMinutes()-date.getTimezoneOffset());form.elements.occurredAt.value=date.toISOString().slice(0,16);
 if(expense){form.elements.category.value=expense.category;form.elements.description.value=expense.description;form.elements.amount.value=expense.amount;form.elements.notes.value=expense.notes||'';form.elements.latitude.value=expense.latitude??'';form.elements.longitude.value=expense.longitude??'';form.elements.locationAccuracy.value=expense.location_accuracy??'';$('#expense-location').value=expense.latitude!=null?`${Number(expense.latitude).toFixed(6)}, ${Number(expense.longitude).toFixed(6)}`:'Localização ainda não capturada';$('#location-help').textContent=expense.latitude!=null?`Localização já registrada${expense.location_accuracy?` · precisão de ${Math.round(expense.location_accuracy)} m`:''}`:'Capture a localização desta despesa.';if(expense.has_receipt){const preview=$('#receipt-preview');preview.querySelector('img').src=expense.receipt_data;preview.querySelector('span').textContent=expense.receipt_name||'Nota fiscal já registrada';preview.hidden=false}}
 else{$('#expense-location').value='Localização ainda não capturada';$('#location-help').textContent='O navegador solicitará permissão para acessar o GPS.'}
 $('#expense-dialog').showModal();
}
function setAdminTab(name){document.querySelectorAll('#admin-nav button').forEach(b=>b.classList.toggle('active',b.dataset.admin===name))}
const adminTitles={users:'Cadastro de usuários',vehicles:'Cadastro de veículos',trips:'Cadastro de viagens',customers:'Cadastro de clientes'};
async function openAdmin(resource){
 setAdminTab(resource);$('#trip-list').hidden=true;$('#trip-detail').hidden=true;$('#admin-view').hidden=false;$('#page-title').textContent=adminTitles[resource];
 let options={customers:[],drivers:[],vehicles:[]};if(resource==='trips')options=await request('/api/admin/options');const {items}=await request(`/api/admin/${resource}`);editingAdminId=null;currentAdminResource=resource;currentAdminItems=items;
 const forms={
  users:`<label>Nome<input name="name" required></label><label>CPF<input name="cpf" inputmode="numeric" maxlength="11" minlength="11" pattern="[0-9]{11}" required placeholder="Somente 11 números"><small class="field-hint">Digite exatamente 11 números, sem pontos ou traço.</small></label><label>Tipo<select name="role" required><option value="driver">Motorista</option><option value="admin">Administrador</option></select></label><label>E-mail<input name="email" type="email" maxlength="254" required placeholder="nome@empresa.com.br"></label><label>Senha inicial<input name="password" type="password" minlength="8" required></label><label>Foto <span class="optional">(até 2 MB)</span><input name="photo" type="file" accept="image/jpeg,image/png,image/webp"></label>`,
  vehicles:`<label>Placa<input name="plate" maxlength="8" required placeholder="ABC1D23"></label><label>Modelo<input name="model" required></label><label>Chassi<input name="chassis" required></label><label>Renavam<input name="renavam" inputmode="numeric" maxlength="11" required></label>`,
  customers:`<label>Nome<input name="name" required></label><label>CNPJ<input name="cnpj" inputmode="numeric" maxlength="18" required></label><label>CEP<input name="cep" inputmode="numeric" maxlength="9" required></label><label>Número<input name="number" required></label><label>Complemento<input name="complement"></label><label>Telefone<input name="phone" type="tel" required></label><label>Nome do contato<input name="contactName" required></label>`,
  trips:`<label>Origem<input name="origin" required></label><label>Destino<input name="destination" required></label><label>Quilometragem<input name="mileage" type="number" min="0.1" step="0.1" required></label><label>Valor do frete<input name="freightValue" type="number" min="0.01" step="0.01" required></label><label>Cliente<select name="customerId" required><option value="">Selecione</option>${options.customers.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label><label>Motorista<select name="driverId" required><option value="">Selecione</option>${options.drivers.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label><label>Veículo<select name="vehicleId" required><option value="">Selecione</option>${options.vehicles.map(x=>`<option value="${x.id}">${esc(x.plate)} · ${esc(x.model)}</option>`).join('')}</select></label>`
 };
 $('#admin-view').innerHTML=`<section class="admin-layout"><form id="admin-form" data-resource="${resource}" class="admin-form"><span id="admin-form-label" class="label">NOVO REGISTRO</span><h2 id="admin-form-title">${adminTitles[resource]}</h2><div class="form-grid">${forms[resource]}</div><button id="admin-save" class="primary wide">Salvar cadastro</button><button id="admin-cancel-edit" type="button" class="secondary wide" hidden>Cancelar edição</button></form><div class="records"><span class="label">REGISTROS</span><h2>Cadastrados</h2><div class="record-list">${renderAdminItems(resource,items)}</div></div></section>`;
}
function renderAdminItems(resource,items){if(!items.length)return '<div class="empty">Nenhum registro cadastrado.</div>';return items.map(x=>{
 if(resource==='users')return `<article class="record"><div><strong>${esc(x.name)}</strong><p>${x.role==='admin'?'Administrador':'Motorista'} · ${esc(x.email)}</p></div><div class="record-side"><span>${esc(x.cpf||'CPF não informado')}</span><button class="edit-expense" data-admin-edit="${x.id}">Editar</button></div></article>`;
 if(resource==='vehicles')return `<article class="record"><div><strong>${esc(x.plate)}</strong><p>${esc(x.model)}</p></div><div class="record-side"><span>Renavam ${esc(x.renavam)}</span><button class="edit-expense" data-admin-edit="${x.id}">Editar</button></div></article>`;
 if(resource==='customers')return `<article class="record"><div><strong>${esc(x.name)}</strong><p>${esc(x.contact_name)} · ${esc(x.phone)}</p></div><div class="record-side"><span>${esc(x.cnpj)}</span><button class="edit-expense" data-admin-edit="${x.id}">Editar</button></div></article>`;
 return `<article class="record"><div><strong>${esc(x.code)} · ${esc(x.origin)} → ${esc(x.destination)}</strong><p>${esc(x.customer_name||'Sem cliente')} · ${esc(x.driver_name)}</p></div><span>${esc(x.plate)} · ${money.format(x.freight_value||0)}</span></article>`
 }).join('')}
function startAdminEdit(id){
 if(currentAdminResource==='trips')return;const item=currentAdminItems.find(x=>x.id==id);if(!item)return;const form=$('#admin-form');editingAdminId=item.id;$('#admin-form-label').textContent='EDITANDO REGISTRO';$('#admin-form-title').textContent=adminTitles[currentAdminResource].replace('Cadastro de','Editar');$('#admin-save').textContent='Salvar alterações';$('#admin-cancel-edit').hidden=false;
 if(currentAdminResource==='users'){form.elements.name.value=item.name;form.elements.cpf.value=item.cpf||'';form.elements.role.value=item.role;form.elements.email.value=item.email;form.elements.password.value='';form.elements.password.required=false;form.elements.password.placeholder='Deixe vazio para manter a senha atual'}
 if(currentAdminResource==='vehicles'){form.elements.plate.value=item.plate;form.elements.model.value=item.model;form.elements.chassis.value=item.chassis;form.elements.renavam.value=item.renavam}
 if(currentAdminResource==='customers'){form.elements.name.value=item.name;form.elements.cnpj.value=item.cnpj;form.elements.cep.value=item.cep;form.elements.number.value=item.address_number;form.elements.complement.value=item.complement||'';form.elements.phone.value=item.phone;form.elements.contactName.value=item.contact_name}
 form.scrollIntoView({behavior:'smooth',block:'start'});
}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';$('#login-error').classList.remove('success');try{user=(await request('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))})).user;showApp();await loadTrips()}catch(err){$('#login-error').textContent=err.message}});
$('#open-company').addEventListener('click',()=>{$('#company-form').reset();$('#company-error').textContent='';$('#company-dialog').showModal()});
$('#close-company').addEventListener('click',()=>$('#company-dialog').close());$('#cancel-company').addEventListener('click',()=>$('#company-dialog').close());
$('#company-form').addEventListener('input',e=>{if(e.target.name==='cnpj')e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,14);if(e.target.name==='cep')e.target.value=e.target.value.replace(/\D/g,'').slice(0,8)});
$('#company-form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));$('#company-error').textContent='';try{if(!validCnpj(data.cnpj))throw new Error('Informe um CNPJ válido.');if(!validEmail(data.email))throw new Error('Informe um e-mail válido.');await request('/api/companies',{method:'POST',body:JSON.stringify(data)});$('#company-dialog').close();$('#login-form').elements.email.value=data.email;$('#login-form').elements.password.value='';$('#login-error').classList.add('success');$('#login-error').textContent='Empresa criada. Entre com o e-mail e a senha cadastrados.'}catch(err){$('#company-error').textContent=err.message}});
$('#logout').addEventListener('click',async()=>{await request('/api/logout',{method:'POST'});location.reload()});
$('#trip-list').addEventListener('click',e=>{const card=e.target.closest('[data-trip]');if(card)openTrip(card.dataset.trip).catch(err=>notify(err.message,'error'))});
$('#admin-nav').addEventListener('click',e=>{const resource=e.target.dataset.admin;if(!resource)return;if(resource==='reviews')loadTrips().catch(err=>notify(err.message,'error'));else openAdmin(resource).catch(err=>notify(err.message,'error'))});
$('#admin-view').addEventListener('input',e=>{if(e.target.name==='cpf')e.target.value=e.target.value.replace(/\D/g,'').slice(0,11)});
$('#admin-view').addEventListener('click',e=>{const id=e.target.dataset.adminEdit;if(id)return startAdminEdit(id);if(e.target.id==='admin-cancel-edit')openAdmin(currentAdminResource).catch(err=>notify(err.message,'error'))});
$('#admin-view').addEventListener('submit',async e=>{if(e.target.id!=='admin-form')return;e.preventDefault();try{const form=e.target,f=new FormData(form),resource=form.dataset.resource,payload=Object.fromEntries(f.entries());delete payload.photo;if(resource==='users'){if(!validCpf(payload.cpf))throw new Error('CPF inválido. Confira os números informados.');if(!validEmail(payload.email))throw new Error('Informe um endereço de e-mail válido.');const file=f.get('photo');if(file&&file.size){if(file.size>2*1024*1024)throw new Error('A foto deve ter até 2 MB.');payload.photoData=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}}const editing=editingAdminId!==null,result=await request(`/api/admin/${resource}${editing?`?id=${editingAdminId}`:''}`,{method:editing?'PUT':'POST',body:JSON.stringify(payload)});notify(resource==='trips'?`Viagem ${result.code} cadastrada.`:editing?'Cadastro atualizado com sucesso.':'Cadastro salvo com sucesso.');await openAdmin(resource)}catch(err){notify(err.message,'error')}});
$('#trip-detail').addEventListener('click',async e=>{try{
 if(e.target.closest('.back'))return loadTrips();const a=e.target.dataset.action;
 if(a==='start'){await request(`/api/trips/${activeTrip.trip.id}/start`,{method:'POST'});notify('Viagem iniciada.');return refreshTrip()}
 if(a==='add')return openExpenseForm();
 if(a==='submit'&&confirm('Enviar a viagem para validação? Depois disso, as despesas não poderão ser alteradas.')){await request(`/api/trips/${activeTrip.trip.id}/submit`,{method:'POST'});notify('Viagem enviada para validação.');await refreshTrip()}
 if(a==='approve'||a==='reject'){await request(`/api/trips/${activeTrip.trip.id}/review`,{method:'POST',body:JSON.stringify({approved:a==='approve',notes:$('#review-notes').value})});notify(a==='approve'?'Viagem aprovada e encerrada.':'Viagem devolvida para correção.');await loadTrips()}
 const edit=e.target.dataset.edit;if(edit){const item=activeTrip.expenses.find(x=>x.id==edit);if(item)return openExpenseForm(item)}
 const del=e.target.dataset.delete;if(del&&confirm('Excluir esta despesa?')){await request(`/api/trips/${activeTrip.trip.id}/expenses?id=${del}`,{method:'DELETE'});await refreshTrip()}
 const receipt=e.target.dataset.receipt;if(receipt){const item=activeTrip.expenses.find(x=>x.id==receipt);$('#receipt-image').src=item.receipt_data;$('#receipt-dialog').showModal()}
}catch(err){notify(err.message,'error')}});
$('#capture-location').addEventListener('click',()=>{const button=$('#capture-location'),help=$('#location-help');if(!navigator.geolocation){help.textContent='GPS não disponível neste dispositivo.';return}button.disabled=true;button.textContent='Obtendo localização...';navigator.geolocation.getCurrentPosition(position=>{const {latitude,longitude,accuracy}=position.coords;$('#expense-form').elements.latitude.value=latitude;$('#expense-form').elements.longitude.value=longitude;$('#expense-form').elements.locationAccuracy.value=accuracy;$('#expense-location').value=`${latitude.toFixed(6)}, ${longitude.toFixed(6)}`;help.textContent=`Localização capturada · precisão aproximada de ${Math.round(accuracy)} m`;button.disabled=false;button.textContent='✓ Atualizar localização'},error=>{const messages={1:'Permissão de localização negada.',2:'Não foi possível determinar a localização.',3:'O GPS demorou para responder. Tente novamente.'};help.textContent=messages[error.code]||'Erro ao acessar o GPS.';button.disabled=false;button.textContent='⌖ Tentar novamente'},{enableHighAccuracy:true,timeout:15000,maximumAge:0})});
$('#expense-form').addEventListener('submit',async e=>{e.preventDefault();try{const f=new FormData(e.target),galleryFile=f.get('receipt'),file=capturedReceiptFile||(galleryFile&&galleryFile.size?galleryFile:null);if(!f.get('latitude')||!f.get('longitude'))throw new Error('Capture a localização GPS antes de salvar a despesa.');let receiptData=null;if(file){if(file.size>5*1024*1024)throw new Error('A imagem deve ter até 5 MB.');receiptData=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}const editing=editingExpenseId!==null,url=`/api/trips/${activeTrip.trip.id}/expenses${editing?`?id=${editingExpenseId}`:''}`;await request(url,{method:editing?'PUT':'POST',body:JSON.stringify({category:f.get('category'),description:f.get('description'),amount:f.get('amount'),occurredAt:f.get('occurredAt'),notes:f.get('notes'),receiptName:file?.name,receiptType:file?.type,receiptData,latitude:f.get('latitude'),longitude:f.get('longitude'),locationAccuracy:f.get('locationAccuracy')})});$('#expense-dialog').close();notify(editing?'Despesa atualizada.':'Despesa registrada.');editingExpenseId=null;await refreshTrip()}catch(err){notify(err.message,'error')}});
function showReceiptPreview(file){const preview=$('#receipt-preview');preview.querySelector('img').src=URL.createObjectURL(file);preview.querySelector('span').textContent=`${file.name} · ${(file.size/1024/1024).toFixed(1)} MB`;preview.hidden=false}
function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null}$('#camera-video').srcObject=null}
async function openRearCamera(){
 if(!navigator.mediaDevices?.getUserMedia){$('#native-camera').click();return}
 $('#camera-dialog').showModal();$('#camera-help').textContent='Solicitando acesso à câmera traseira...';
 try{try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{exact:'environment'}},audio:false})}catch{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false})}$('#camera-video').srcObject=cameraStream;$('#camera-help').textContent='Posicione toda a nota fiscal dentro da imagem.'}catch{$('#camera-help').textContent='Não foi possível abrir a câmera. Verifique a permissão do navegador.'}
}
$('#open-camera').addEventListener('click',openRearCamera);
$('#close-camera').addEventListener('click',()=>{stopCamera();$('#camera-dialog').close()});
$('#camera-dialog').addEventListener('close',stopCamera);
$('#take-photo').addEventListener('click',()=>{const video=$('#camera-video');if(!cameraStream||!video.videoWidth){$('#camera-help').textContent='Aguarde a câmera carregar.';return}const max=1600,scale=Math.min(1,max/Math.max(video.videoWidth,video.videoHeight)),canvas=$('#camera-canvas');canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(!blob)return;capturedReceiptFile=new File([blob],`nota-${Date.now()}.jpg`,{type:'image/jpeg'});$('#expense-form').elements.receipt.value='';showReceiptPreview(capturedReceiptFile);stopCamera();$('#camera-dialog').close()},'image/jpeg',.86)});
$('#expense-form').elements.receipt.addEventListener('change',e=>{const file=e.target.files[0];capturedReceiptFile=null;if(file)showReceiptPreview(file);else $('#receipt-preview').hidden=true});
$('#native-camera').addEventListener('change',e=>{const file=e.target.files[0];if(file){capturedReceiptFile=file;$('#expense-form').elements.receipt.value='';showReceiptPreview(file)}});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#expense-dialog').close());$('[data-close-receipt]').onclick=()=>$('#receipt-dialog').close();boot();
