// Integration checks in a disposable local PostgreSQL schema. Never uses business data.
require('dotenv').config({quiet:true});
const {Client}=require('pg'),{spawn,spawnSync}=require('node:child_process'),path=require('node:path'),fs=require('node:fs');
const root=path.join(__dirname,'..'),name=`rota_certa_qa_${Date.now()}`,base='http://127.0.0.1:18080',results=[];
const password='QaTemporary123!',png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
let server,created=false,qa,admin;
function check(label,ok,detail=''){results.push({label,ok,detail});console.log(`${ok?'PASS':'FAIL'} ${label}${detail?' '+detail:''}`)}
async function req(label,route,method='GET',body,cookie='',expected=200){const r=await fetch(base+route,{method,headers:{'Content-Type':'application/json',Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{data=raw}check(label,r.status===expected,`HTTP ${r.status}`);return {data,cookie:r.headers.get('set-cookie')?.split(';')[0]||'',status:r.status}}
function cnpj(seed){let s=seed;for(const w of [[5,4,3,2,9,8,7,6,5,4,3,2],[6,5,4,3,2,9,8,7,6,5,4,3,2]]){let r=w.reduce((a,n,i)=>a+n*Number(s[i]),0)%11;s+=r<2?'0':String(11-r)}return s}
async function run(){
 const source=new URL(process.env.DATABASE_URL);if(!['localhost','127.0.0.1','[::1]'].includes(source.hostname))throw new Error('This check only supports a local PostgreSQL server');
 admin=new Client({connectionString:source.href});await admin.connect();await admin.query(`CREATE SCHEMA "${name}"`);created=true;source.searchParams.set('options',`-c search_path=${name}`);
 const env={...process.env,DATABASE_URL:source.href,PORT:'18080',NODE_ENV:'test',GOOGLE_MAPS_API_KEY:''};
 qa=new Client({connectionString:source.href});await qa.connect();
 const schema=fs.readFileSync(path.join(__dirname,'migrate-to-postgres.js'),'utf8').match(/const schema = `([\s\S]*?)`;/)?.[1];if(!schema)throw new Error('Base schema not found');await qa.query(schema);
 for(const file of ['migrate-admin-modules.js','migrate-multicompany.js']){const r=spawnSync(process.execPath,[path.join(__dirname,file)],{env,cwd:root,encoding:'utf8'});if(r.status!==0)throw new Error('Migration failed: '+file)}
 server=spawn(process.execPath,['server.js'],{cwd:root,env,stdio:['ignore','pipe','pipe']});let logs='';server.stdout.on('data',x=>logs+=x);server.stderr.on('data',()=>{});
 await new Promise((resolve,reject)=>{let count=0;const timer=setInterval(()=>{if(logs.includes('disponíveis')){clearInterval(timer);resolve()}else if(++count>50||server.exitCode!==null){clearInterval(timer);reject(new Error('Test server did not start'))}},100)});
 await req('Site institucional','/');await req('Página do sistema','/motorista.html');await req('JavaScript','/app.js');await req('CSS','/styles.css');
 await req('API exige autenticação','/api/trips','GET',undefined,'',401);
 for(const [n,seed] of [['a','123456780001'],['b','987654320001']])await req('Cadastro empresa '+n,'/api/companies','POST',{name:'QA '+n,cnpj:cnpj(seed),cep:'01001000',email:`qa-${n}@example.test`,responsibleName:'QA Admin',password},'',201);
 await req('Senha incorreta','/api/login','POST',{email:'qa-a@example.test',password:'wrong'},'',401);
 const a=(await req('Login admin A','/api/login','POST',{email:'qa-a@example.test',password})).cookie,b=(await req('Login admin B','/api/login','POST',{email:'qa-b@example.test',password})).cookie;
 await req('Sessão autenticada','/api/me','GET',undefined,a);
 await req('Cadastro motorista','/api/admin/users','POST',{name:'QA Driver',email:'qa-driver@example.test',password,cpf:'52998224725',role:'driver'},a,201);
 const users=(await req('Listar usuários','/api/admin/users','GET',undefined,a)).data.items,driver=users.find(x=>x.role==='driver');
 await req('Editar motorista','/api/admin/users?id='+driver.id,'PUT',{name:'QA Driver Editado',email:driver.email,cpf:'52998224725',role:'driver'},a);
 const d=(await req('Login motorista','/api/login','POST',{email:driver.email,password})).cookie;
 await req('Motorista sem acesso admin','/api/admin/users','GET',undefined,d,403);
 await req('Cadastro cliente mínimo','/api/admin/customers','POST',{name:'QA Cliente'},a,201);
 const customer=(await req('Listar clientes','/api/admin/customers','GET',undefined,a)).data.items[0];
 await req('Editar cliente','/api/admin/customers?id='+customer.id,'PUT',{name:'QA Cliente Editado',fleet:'2',contact:'QA'},a);
 const vehicleData={plate:'QAT1A23',model:'QA Truck',chassis:'QA123456789012345',renavam:'12345678901',fuelConsumption:3,axleCount:6};
 await req('Cadastro veículo','/api/admin/vehicles','POST',vehicleData,a,201);
 const vehicle=(await req('Listar veículos','/api/admin/vehicles','GET',undefined,a)).data.items[0];
 await req('Editar veículo','/api/admin/vehicles?id='+vehicle.id,'PUT',{...vehicleData,fuelConsumption:3.5},a);
 await req('Opções administrativas','/api/admin/options','GET',undefined,a);
 const tripData={origin:'São Paulo',destination:'Santos',mileage:90,freightValue:1500,driverId:driver.id,vehicleId:vehicle.id,customerId:customer.id,startDate:'2026-09-25',endDate:'2026-09-26'};
 await req('Rejeitar datas invertidas','/api/admin/trips','POST',{...tripData,endDate:'2026-09-24'},a,400);
 await req('Rejeitar vínculos de outra empresa','/api/admin/trips','POST',tripData,b,400);
 await req('Cadastrar viagem','/api/admin/trips','POST',tripData,a,201);
 const trip=(await req('Listar viagens admin','/api/admin/trips','GET',undefined,a)).data.items[0],p='/api/trips/'+trip.id;
 await req('Editar viagem','/api/admin/trips?id='+trip.id,'PUT',{...tripData,mileage:95},a);
 const summary='/api/admin/trips/'+trip.id+'/summary';
 await req('Resumo exige login',summary,'GET',undefined,'',401);
 await req('Resumo exclusivo administrador',summary,'GET',undefined,d,403);
 await req('Resumo isolado por empresa',summary,'GET',undefined,b,404);
 await req('Resumo de viagem inexistente','/api/admin/trips/2147483647/summary','GET',undefined,a,404);
 const emptySummary=(await req('Resumo sem documentos',summary,'GET',undefined,a)).data;
 check('Resumo vazio com total zero',emptySummary.includes('Nenhum documento anexado')&&emptySummary.includes('R$\u00a00,00'));
 check('Cabeçalho do resumo completo',['São Paulo','Santos','25/09/2026','26/09/2026','95 km','1.500,00','QA Cliente Editado','QA Driver Editado','QAT1A23','QA Truck'].every(value=>emptySummary.includes(value)));
 await req('Estilo do resumo','/trip-summary.css');
 const isolated=(await req('Listagem de outra empresa','/api/trips','GET',undefined,b)).data.trips;check('Empresa B não vê viagens de A',isolated.length===0);
 await req('Bloquear leitura de outra empresa',p,'GET',undefined,b,404);
 await req('Bloquear edição de outra empresa','/api/admin/trips?id='+trip.id,'PUT',tripData,b,400);
 await req('Listar viagens motorista','/api/trips','GET',undefined,d);
 const exp={category:'Combustível',description:'QA Despesa',amount:120,occurredAt:'2026-09-25T12:00:00Z',latitude:-23.55,longitude:-46.63,locationAccuracy:10,receiptData:png,receiptType:'image/png',receiptName:'qa.png'};
 await req('Bloquear despesa antes do início',p+'/expenses','POST',exp,d,409);
 await req('Iniciar viagem',p+'/start','POST',{},d);await req('Bloquear segundo início',p+'/start','POST',{},d,409);
 await req('Bloquear envio sem despesas',p+'/submit','POST',{},d,400);
 await req('Rejeitar despesa sem GPS',p+'/expenses','POST',{...exp,latitude:null,longitude:null},d,400);
 await req('Criar despesa com comprovante',p+'/expenses','POST',exp,d,201);
 let detail=(await req('Detalhes e comprovante',p,'GET',undefined,d)).data;const expense=detail.expenses[0];check('Comprovante persistido',expense.receipt_data===png);
 await req('Editar despesa',p+'/expenses?id='+expense.id,'PUT',{...exp,amount:140},d);
 await req('Excluir despesa',p+'/expenses?id='+expense.id,'DELETE',undefined,d);
 await req('Recriar despesa',p+'/expenses','POST',exp,d,201);
 const docPath='/api/admin/trips/'+trip.id+'/documents',doc={documentType:'CTE',description:'QA Documento',fileName:'qa.png',fileType:'image/png',fileData:png};
 const docId=(await req('CTE sem valor ou KM',docPath,'POST',doc,a,201)).data.id;
 await req('Bloquear documento de outra empresa',docPath,'POST',doc,b,404);
 await req('Abastecimento exige valor/KM',docPath,'POST',{...doc,documentType:'Abastecimento'},a,400);
 await req('Anexar abastecimento',docPath,'POST',{...doc,documentType:'Abastecimento',amount:100,km:2000},a,201);
 await req('Anexar outros gastos',docPath,'POST',{...doc,documentType:'Outros gastos',amount:20},a,201);
 const summaryResponse=await fetch(base+summary,{headers:{Cookie:a}}),summaryHtml=await summaryResponse.text();
 check('Resumo servido como HTML sem cache',summaryResponse.headers.get('content-type').includes('text/html')&&summaryResponse.headers.get('cache-control')==='no-store');
 check('Resumo inclui documentos e soma 120 reais',['CTE','Abastecimento','Outros gastos','2.000','QA Documento','R$\u00a0120,00'].every(value=>summaryHtml.includes(value)));
 await qa.query('UPDATE trip_documents SET description=$1 WHERE id=$2',['<script>alert("QA")</script> & teste',docId]);
 const escapedSummary=(await req('Resumo com texto especial',summary,'GET',undefined,a)).data;
 check('Resumo escapa texto de documentos',escapedSummary.includes('&lt;script&gt;')&&!escapedSummary.includes('<script>'));
 await qa.query('UPDATE trip_documents SET amount=0.10 WHERE trip_id=$1 AND document_type=$2',[trip.id,'Abastecimento']);
 await qa.query('UPDATE trip_documents SET amount=0.20 WHERE trip_id=$1 AND document_type=$2',[trip.id,'Outros gastos']);
 const cents=(await req('Resumo com centavos',summary,'GET',undefined,a)).data;check('Soma exata dos centavos',cents.includes('R$\u00a00,30'));
 await req('Listar documentos',docPath,'GET',undefined,a);await req('Abrir documento','/api/admin/trip-documents/'+docId+'/file','GET',undefined,a);
 await req('Bloquear arquivo de outra empresa','/api/admin/trip-documents/'+docId+'/file','GET',undefined,b,404);
 await req('Excluir documento','/api/admin/trip-documents/'+docId,'DELETE',undefined,a);
 await req('Enviar viagem',p+'/submit','POST',{},d);await req('Bloquear despesa após envio',p+'/expenses','POST',exp,d,409);
 await req('Motorista não aprova viagem',p+'/review','POST',{approved:true},d,403);
 await req('Solicitar correção',p+'/review','POST',{approved:false,notes:'QA revisão'},a);
 detail=(await req('Verificar devolução',p,'GET',undefined,d)).data;check('Status voltou a andamento',detail.trip.status==='in_progress');
 await req('Reenviar viagem',p+'/submit','POST',{},d);await req('Aprovar e encerrar',p+'/review','POST',{approved:true,notes:'QA aprovado'},a);
 detail=(await req('Verificar encerramento',p,'GET',undefined,d)).data;check('Status encerrada',detail.trip.status==='closed');
 await req('Bloquear despesa após encerramento',p+'/expenses','POST',exp,d,409);
 const inv='/api/admin/purchase-invoices',invoice=(await req('Enviar nota de compra',inv,'POST',{imageData:png,imageType:'image/png',imageName:'qa.png'},a,201)).data.id;
 await req('Listar notas',inv,'GET',undefined,a);await req('Abrir imagem da nota',inv+'/'+invoice+'/image','GET',undefined,a);
 await req('Rejeitar rateio vazio',inv+'/'+invoice+'/justify','PUT',{supplier:'QA',allocations:[]},a,400);
 await req('Justificar nota',inv+'/'+invoice+'/justify','PUT',{supplier:'QA Fornecedor',allocations:[{customerId:customer.id,material:'QA Material',amount:50,noteDate:'2026-09-25'}]},a);
 const note=(await req('Detalhar nota',inv+'/'+invoice,'GET',undefined,a)).data;check('Nota concluída com rateio',note.status==='completed'&&note.allocations.length===1);
 await req('Bloquear nota de outra empresa',inv+'/'+invoice,'GET',undefined,b,404);
 await req('Histórico de fretes vazio','/api/admin/freight-quotes','GET',undefined,a);
 await req('Frete informa chave ausente','/api/admin/freight-quote','POST',{origin:'São Paulo',destination:'Santos',vehicleId:vehicle.id,fuelPrice:6,driverPayment:200},a,503);
 await req('Logout','/api/logout','POST',{},a);const replay=await req('Token anterior após logout (diagnóstico)','/api/me','GET',undefined,a);check('Logout revoga sessão no servidor',replay.data.user===null);
}
run().catch(e=>{check('Execução completa',false,e.message)}).finally(async()=>{
 if(server&&server.exitCode===null){server.kill();await new Promise(resolve=>{server.once('exit',resolve);setTimeout(resolve,3000)})}if(qa)await qa.end();
 if(created&&admin){await admin.query(`DROP SCHEMA "${name}" CASCADE`);check('Schema temporário removido',true)}if(admin)await admin.end();
 fs.writeFileSync(path.join(root,'VALIDACAO-FLUXOS.json'),JSON.stringify({date:new Date().toISOString(),mode:'API HTTP real, schema temporário isolado, sem Google externo',results},null,2));console.log(JSON.stringify({passed:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).length}));process.exitCode=results.some(x=>!x.ok)?1:0;
});
